server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
      username: ""
      password: ""
      url: "jdbc:h2:./taskManager"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  level:
    ROOT: INFO